Repository bai-project-recipies/bai-project-recipies, pull requests merged in 2020-04, with the labels that each got.

#2 2. Add participants
  README.md
Labels: documentation

#3 2. Add participants - bugfix
  README.md
Labels: bug, documentation

#4 4. Import Vuetify and add sass to webpack config
  package-lock.json
  package.json
  src/App.vue
  src/Vuetify.js
  src/components/NavigationComponent.vue
  src/main.js
  src/styles/_NavigationComponent.scss
  webpack.config.js
Labels: enhancement

#6 6. Make first request to recipe API
  package-lock.json
  package.json
  src/App.vue
  src/components/RecipieComponent.vue
  src/shared/constants.js
  src/styles/_RecipieComponent.scss
Labels: enhancement

#7 10. Present recipe search data - create components (without criteria)
  src/App.vue
  src/components/RecipeComponent.vue
  src/components/RecipeSearchFormComponent.vue
  src/components/RecipieComponent.vue
  src/components/RecipiesComponent.vue
  src/shared/constants.js
  src/styles/_RecipeComponent.css
  src/styles/_RecipeSearchFormComponent.css
  src/styles/_RecipieComponent.scss
  src/styles/_RecipiesComponent.css
Labels: enhancement

#8 12. Make criteria for search recipies
  src/App.vue
  src/components/RecipeSearchFormComponent.vue
  src/components/RecipesSearchGeneral/RecipeComponent.vue
  src/components/RecipesSearchGeneral/RecipeSearchFormComponent.vue
  src/components/RecipesSearchGeneral/RecipiesComponent.vue
  src/components/RecipiesComponent.vue
  src/components/shared/FormCriteriaCheckBoxComponent.vue
  src/shared/constants.js
  src/styles/_NavigationComponent.scss
  src/styles/_RecipeComponent.css
  src/styles/_RecipesComponent.css
  src/styles/_RecipiesComponent.css
Labels: enhancement

#9 9. Make routing in nav
  package-lock.json
  package.json
  src/App.vue
  src/components/NavigationComponent.vue
  src/components/RecipesSearchGeneral/RecipeSearchFormComponent.vue
  src/components/RecipesSearchGeneral/RecipiesComponent.vue
  src/components/RecipiesSearchByIngredients/RecipesSearchByIngredients.vue
  src/main.js
  src/routes/index.js
  src/styles/_NavigationComponent.css
Labels: enhancement

#35 Feature/add database api
  src/components/RecipesSearchGeneral/RecipeComponent.vue
  src/shared/DBHandling.js
  src/shared/constants.js
Labels: backend, enhancement, first-priority

#37 #19 Make search by ingredients component
  src/components/RecipiesSearchByIngredients/RecipeIngredientsComponent.vue
  src/components/RecipiesSearchByIngredients/RecipeSearchByIngredientSearchFormComponent.vue
  src/components/RecipiesSearchByIngredients/RecipesSearchByIngredients.vue
Labels: enhancement

#46 Add base to router
  src/routes/index.js
Labels: bug, deployment, enhancement

#44 Migrate to use vue-cli
  .babelrc
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/components/GenerateMealPlan/DayMealPlan.vue
  src/components/GenerateMealPlan/GenerateMealPlan.vue
  src/components/GenerateMealPlan/GenerateMealPlanSearchFormComponent.vue
  src/components/GenerateMealPlan/WeekMealPlan.vue
  src/components/NavigationComponent.vue
  src/main.js
  src/shared/DBHandling.js
  webpack.config.js
Labels: dependencies, deployment, help wanted

#61 #11 Fix the problem with diet on fast search
  package-lock.json
  src/components/RecipesSearchGeneral/RecipeSearchFormComponent.vue
Labels: bug

#64 #63 customize browser tab
  index.html
  src/assets/favicon.png
Labels: style

#67 Feature/improved like
  package-lock.json
  src/components/RecipesSearchGeneral/RecipeComponent.vue
  src/components/RecipiesSearchByIngredients/RecipeIngredientsComponent.vue
  src/components/RecipiesSearchByNutrients/RecipeNutrientsComponent.vue
  src/shared/DBHandling.js
Labels: style
